export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_COMPLETE = 'SIGN_IN_COMPLETE';

export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';
export const SIGN_OUT_COMPLETE = 'SIGN_OUT_COMPLETE';
